
sonar.projectKey=PrasoonPortfolioApp
sonar.projectName=PrasoonPortfolioApp
sonar.projectVersion=1.0
sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=sqp_f124290ade0b70ea3d12d98b66f0d4692c5a5166
sonar.javascript.lcov.reportPaths=coverage/lcov.info