import { PortfolioColors } from './colors';

export const PortfolioProjects = [
  {
    id: 1,
    projectImage: require('../assets/Images/TractorSupplyProjectImage.png'),
    projectName: 'Consumer Mobile Application',
    projectTiming: 'July 2021',
    projectTags: ['Mobile App', 'Retail Tech', 'Neighbor Club'],
    projectShortDescription:
      'Developed a scalable React Native mobile application for Tractor Supply Company delivering seamless retail shopping experiences, AI-powered recommendations, real-time inventory access, secure checkout flows, and omnichannel customer engagement across iOS and Android platforms.',
    projectTechStack: [
      {
        projectTitle: 'React Native',
        projectTitleLogo: require('../assets/Images/ReactNativeTechStack.png'),
        projectTitleTopView: 0,
        projectTitleLeftView: 170,
        projectTitleWidth: 140,
        projectTitleBackgroundColor: PortfolioColors.classicChalk,
        projectIconWidth: 12,
        projectIconHeight: 15,
        projectTechNameColor: PortfolioColors.black,
      },
      {
        projectTitle: 'Typescript',
        projectTitleLogo: require('../assets/Images/TypescriptTechStack.png'),
        projectTitleTopView: -15,
        projectTitleLeftView: 10,
        projectTitleWidth: 143,
        projectTitleBackgroundColor: PortfolioColors.buttercupYellow,
        projectIconWidth: 15,
        projectIconHeight: 12,
        projectTechNameColor: PortfolioColors.black,
      },
      {
        projectTitle: 'Redux JS',
        projectTitleLogo: require('../assets/Images/JavascriptTechStack.png'),
        projectTitleTopView: -10,
        projectTitleLeftView: 140,
        projectTitleWidth: 112,
        projectTitleBackgroundColor: PortfolioColors.brightOrange,
        projectIconWidth: 13.5,
        projectIconHeight: 14.3,
        projectTechNameColor: PortfolioColors.white,
      },
      {
        projectTitle: 'Unit Testing',
        projectTitleLogo: require('../assets/Images/ReactNativeTechStack.png'),
        projectTitleTopView: -5,
        projectTitleLeftView: 0,
        projectTitleWidth: 144,
        projectTitleBackgroundColor: PortfolioColors.seaShellWhite,
        projectIconWidth: 12,
        projectIconHeight: 15,
        projectTechNameColor: PortfolioColors.black,
      },
    ],
    otherTechStack: [
      {
        projectTitle: 'Github',
        projectTitleLogo: require('../assets/Images/GithubTechStack.png'),
        projectTitleTopView: -25,
        projectTitleLeftView: 5,
        projectTitleWidth: 108,
        projectTitleBackgroundColor: PortfolioColors.buttercupYellow,
        projectIconWidth: 15,
        projectIconHeight: 15,
        projectTechNameColor: PortfolioColors.black,
      },
      {
        projectTitle: 'Sonarqube',
        projectTitleLogo: require('../assets/Images/SonarqubeTechStack.png'),
        projectTitleTopView: -10,
        projectTitleLeftView: 35,
        projectTitleWidth: 136,
        projectTitleBackgroundColor: PortfolioColors.darkOliveGreen,
        projectIconWidth: 15,
        projectIconHeight: 15,
        projectTechNameColor: PortfolioColors.white,
      },
    ],
    productionSupportTechStack: [
      {
        projectTitle: 'Quantum Metrics',
        projectTitleLogo: require('../assets/Images/QuantumMetricsTechStack.png'),
        projectTitleTopView: -40,
        projectTitleLeftView: 15,
        projectTitleWidth: 168,
        projectTitleBackgroundColor: PortfolioColors.oxfordWhite,
        projectIconWidth: 15,
        projectIconHeight: 12,
        projectTechNameColor: PortfolioColors.black,
      },
      {
        projectTitle: 'Dynatrace',
        projectTitleLogo: require('../assets/Images/ReactTechStack.png'),
        projectTitleTopView: -95,
        projectTitleLeftView: 215,
        projectTitleWidth: 120,
        projectTitleBackgroundColor: PortfolioColors.deepOrange,
        projectIconWidth: 15,
        projectIconHeight: 9,
        projectTechNameColor: PortfolioColors.white,
      },
      {
        projectTitle: 'Firebase',
        projectTitleLogo: require('../assets/Images/FirebaseTechStack.png'),
        projectTitleTopView: -60,
        projectTitleLeftView: 155,
        projectTitleWidth: 108,
        projectTitleBackgroundColor: PortfolioColors.darkOlive,
        projectIconWidth: 12,
        projectIconHeight: 15,
        projectTechNameColor: PortfolioColors.white,
      },
    ],
    isActivilyWorking: false,
  },
  {
    id: 2,
    projectImage: require('../assets/Images/TaskProjectImage.png'),
    projectName: 'Task Managment Application',
    projectTiming: 'April 2026',
    projectTags: ['Mobile App', 'Task Managment'],
    projectShortDescription:
      'Developed a cross-platform task management mobile application using React Native focused on team collaboration, real-time task tracking, and workflow management with a scalable and user-friendly architecture.',
    projectTechStack: [
      {
        projectTitle: 'React Native',
        projectTitleLogo: require('../assets/Images/ReactNativeTechStack.png'),
        projectTitleTopView: 0,
        projectTitleLeftView: 170,
        projectTitleWidth: 140,
        projectTitleBackgroundColor: PortfolioColors.classicChalk,
        projectIconWidth: 12,
        projectIconHeight: 15,
        projectTechNameColor: PortfolioColors.black,
      },
      {
        projectTitle: 'Typescript',
        projectTitleLogo: require('../assets/Images/TypescriptTechStack.png'),
        projectTitleTopView: -15,
        projectTitleLeftView: 10,
        projectTitleWidth: 143,
        projectTitleBackgroundColor: PortfolioColors.buttercupYellow,
        projectIconWidth: 15,
        projectIconHeight: 12,
        projectTechNameColor: PortfolioColors.black,
      },
      {
        projectTitle: 'Redux Toolkit',
        projectTitleLogo: require('../assets/Images/ReactTechStack.png'),
        projectTitleTopView: -30,
        projectTitleLeftView: 195,
        projectTitleWidth: 144,
        projectTitleBackgroundColor: PortfolioColors.darkOliveGreen,
        projectIconWidth: 15,
        projectIconHeight: 9,
        projectTechNameColor: PortfolioColors.paleGrey,
      },
    ],
    otherTechStack: [
      {
        projectTitle: 'Github',
        projectTitleLogo: require('../assets/Images/GithubTechStack.png'),
        projectTitleTopView: -25,
        projectTitleLeftView: 5,
        projectTitleWidth: 108,
        projectTitleBackgroundColor: PortfolioColors.buttercupYellow,
        projectIconWidth: 15,
        projectIconHeight: 15,
        projectTechNameColor: PortfolioColors.black,
      },
      {
        projectTitle: 'Play Store',
        projectTitleLogo: require('../assets/Images/PlayStoreTechStack.png'),
        projectTitleTopView: -65,
        projectTitleLeftView: 190,
        projectTitleWidth: 135,
        projectTitleBackgroundColor: PortfolioColors.paleGrey,
        projectIconWidth: 15,
        projectIconHeight: 15,
        projectTechNameColor: PortfolioColors.black,
      },
      {
        projectTitle: 'App Store',
        projectTitleLogo: require('../assets/Images/AppStoreTechStack.png'),
        projectTitleTopView: -25,
        projectTitleLeftView: 10,
        projectTitleWidth: 133.5,
        projectTitleBackgroundColor: PortfolioColors.mintGreen,
        projectIconWidth: 15,
        projectIconHeight: 15,
        projectTechNameColor: PortfolioColors.black,
      },
    ],
    productionSupportTechStack: [],
    isActivilyWorking: false,
  },
  {
    id: 3,
    projectImage: '',
    projectName: 'Prasoon Portfolio App',
    projectTiming: 'May 2026',
    projectTags: ['Cross Platform', 'Performance Optimization'],
    projectShortDescription:
      'A curated collection of my software projects, technical expertise, and development achievements.',
    projectTechStack: [
      {
        projectTitle: 'React Native',
        projectTitleLogo: require('../assets/Images/ReactNativeTechStack.png'),
        projectTitleTopView: 0,
        projectTitleLeftView: 170,
        projectTitleWidth: 140,
        projectTitleBackgroundColor: PortfolioColors.classicChalk,
        projectIconWidth: 12,
        projectIconHeight: 15,
        projectTechNameColor: PortfolioColors.black,
      },
      {
        projectTitle: 'Typescript',
        projectTitleLogo: require('../assets/Images/TypescriptTechStack.png'),
        projectTitleTopView: -15,
        projectTitleLeftView: 10,
        projectTitleWidth: 143,
        projectTitleBackgroundColor: PortfolioColors.buttercupYellow,
        projectIconWidth: 15,
        projectIconHeight: 12,
        projectTechNameColor: PortfolioColors.black,
      },
      {
        projectTitle: 'Redux Toolkit',
        projectTitleLogo: require('../assets/Images/ReactTechStack.png'),
        projectTitleTopView: -30,
        projectTitleLeftView: 195,
        projectTitleWidth: 144,
        projectTitleBackgroundColor: PortfolioColors.darkOliveGreen,
        projectIconWidth: 15,
        projectIconHeight: 9,
        projectTechNameColor: PortfolioColors.paleGrey,
      },
      {
        projectTitle: 'CI/CD Pipeline',
        projectTitleLogo: require('../assets/Images/CICDPipelineTechStack.png'),
        projectTitleTopView: -20,
        projectTitleLeftView: 135,
        projectTitleWidth: 144,
        projectTitleBackgroundColor: PortfolioColors.cheeseYellow,
        projectIconWidth: 15,
        projectIconHeight: 15,
        projectTechNameColor: PortfolioColors.black,
      },
    ],
    otherTechStack: [
      {
        projectTitle: 'Github',
        projectTitleLogo: require('../assets/Images/GithubTechStack.png'),
        projectTitleTopView: -25,
        projectTitleLeftView: 5,
        projectTitleWidth: 108,
        projectTitleBackgroundColor: PortfolioColors.buttercupYellow,
        projectIconWidth: 15,
        projectIconHeight: 15,
        projectTechNameColor: PortfolioColors.black,
      },
      {
        projectTitle: 'Sonarqube',
        projectTitleLogo: require('../assets/Images/SonarqubeTechStack.png'),
        projectTitleTopView: -10,
        projectTitleLeftView: 35,
        projectTitleWidth: 136,
        projectTitleBackgroundColor: PortfolioColors.darkOliveGreen,
        projectIconWidth: 15,
        projectIconHeight: 15,
        projectTechNameColor: PortfolioColors.white,
      },
      {
        projectTitle: 'Docker',
        projectTitleLogo: require('../assets/Images/DockerTechStack.png'),
        projectTitleTopView: -80,
        projectTitleLeftView: 235,
        projectTitleWidth: 108,
        projectTitleBackgroundColor: PortfolioColors.cheeseYellow,
        projectIconWidth: 15,
        projectIconHeight: 15,
        projectTechNameColor: PortfolioColors.black,
      },
    ],
    productionSupportTechStack: [],
    isActivilyWorking: true,
  },
];
