export const WorkExperienceConst = [
  {
    id: 1,
    profileName: 'React Native Developer',
    companyName: 'Scans.AI',
    companyUrl: 'https://scans.ai',
    isCompanyPresentEmployee: true,
    companyDurationStart: 'April 2026',
    companyDurationEnd: '',
    companyDescription: 'Car Scanning and Insurance Based Company',
    isAppLink: true,
    appName: 'ScansAI',
    appLink: '',
    isTechSkills: true,
    techSkills: [
      'React Native',
      'Typescript',
      'Redux',
      'Redux-Persistent',
      'Jest',
      'Testing Library',
    ],
    isOtherSkills: true,
    otherSkills: ['Git', 'Firebase'],
    isAgile: true,
    isCICD: true,
    isExperienceLetter: false,
    experienceLetterName: '',
    isProjects: true,
    projectName: 'Ride E-Hailing',
    projectDescription:
      '• Scanning car using mobile app.\n\n• Cached Images using react-native-fast-image.\n',
    isProjectDurationEnd: false,
    projectDurationStart: 'April 2026',
    projectDurationEnd: '',
    iTSectorBased: 'Product',
    isContractor: false,
    contactorCompanyName: '',
    contactorCompanyUrl: '',
    isProductionSupport: true,
    prodSupportTools: ['Firebase Crashlytics', 'Sentry'],
    isAwardsGiven: false,
    awards: [],
  },
  {
    id: 2,
    profileName: 'Technology Lead',
    companyName: 'Infosys',
    companyUrl: 'https://www.infosys.com',
    isCompanyPresentEmployee: false,
    companyDurationStart: 'July 2021',
    companyDurationEnd: 'Mar 2026',
    companyDescription:
      'Global leader in Next-Generation Digital services, Consulting, and AI-powered Enterprise Solutions',
    isAppLink: true,
    appName: 'TractorSupply Co.',
    appLink:
      'https://play.google.com/store/apps/details?id=com.consumerapp_v1&hl=en_IN',
    isTechSkills: true,
    techSkills: [
      'React Native',
      'Typescript',
      'Redux',
      'Restful APIs',
      'Payment Integration',
      'Google Maps',
      'Jest',
      'Testing Library',
    ],
    isOtherSkills: true,
    otherSkills: ['Git', 'Firebase', 'React DevTools', 'FlashLight', 'AEM'],
    isAgile: true,
    isCICD: true,
    isExperienceLetter: true,
    experienceLetterName: 'Infosys Relieving Letter',
    isProjects: true,
    projectName: 'Consumer Mobile App',
    projectDescription:
      '• Led the end-to-end development of a Consumer Mobile App, optimizing memory management and refining API calls, which reduced crashes by 35% and improved load speed by 30%.\n\n• Refactored Redux-based state management, modularizing reducers and improving action efficiency, which enhanced performance and reduced redundant code by 40%.\n\n• Integrated Google Maps API & third-party SDKs, enabling real-time location tracking and interactive features, which led to a 25% increase in session duration.\n\n• Spearheaded unit & integration testing using Jest and React Native Testing Library, achieving 100% test coverage and reducing post-release defects by 50%.\n\n• Automated CI/CD pipelines (Fastlane, Bitrise, GitHub Actions), cutting deployment time by 50%.\n',
    isProjectDurationEnd: true,
    projectDurationStart: 'August 2021',
    projectDurationEnd: 'Mar 2026',
    iTSectorBased: 'Service',
    isContractor: true,
    contactorCompanyName: 'TractorSupply',
    contactorCompanyUrl: 'https://www.tractorsupply.com',
    isProductionSupport: true,
    prodSupportTools: ['Firebase Crashlytics', 'Quantum Metrics', 'Dynatrace'],
    isAwardsGiven: true,
    awards: ['3P Award - Productivity, Performance & Process Excellence'],
  },
  {
    id: 3,
    profileName: 'React Native Developer',
    companyName: 'Wizlite Innovation Center',
    companyUrl: 'https://wizlite.in/#html',
    isCompanyPresentEmployee: false,
    companyDurationStart: 'Jan 2021',
    companyDurationEnd: 'Mar 2021',
    companyDescription:
      'Software Development Company',
    isAppLink: false,
    appName: '',
    appLink:
      '',
    isTechSkills: true,
    techSkills: [
      'React Native',
      'Javascript',
      'Redux',
      'Restful APIs',
    ],
    isOtherSkills: true,
    otherSkills: ['GitLab', 'Firebase'],
    isAgile: false,
    isCICD: false,
    isExperienceLetter: true,
    experienceLetterName: 'Wizlite Experience Letter',
    isProjects: true,
    projectName: 'Trade License Application',
    projectDescription:
      '• Developed and launched a React Native application, optimizing rendering logic and implementing virtualized lists, which improved UI responsiveness by 25%.\n\n• Built scalable UI components using modular design principles, reducing redundant code by 30% and improving maintainability.\n\n• Successfully deployed the Trade License App on the Google Play Store, achieving 1,000+ downloads within the first month.\n',
    isProjectDurationEnd: true,
    projectDurationStart: 'Jan 2021',
    projectDurationEnd: 'Mar 2021',
    iTSectorBased: 'Product',
    isContractor: false,
    contactorCompanyName: '',
    contactorCompanyUrl: '',
    isProductionSupport: false,
    prodSupportTools: [],
    isAwardsGiven: false,
    awards: [],
  },
  {
    id: 4,
    profileName: 'Field Application Engineer',
    companyName: 'RKE',
    companyUrl: 'https://www.rkelectro.com',
    isCompanyPresentEmployee: false,
    companyDurationStart: 'Nov 2019',
    companyDurationEnd: 'Nov 2020',
    companyDescription:
      'Leading Electronics Components Distributor.',
    isAppLink: false,
    appName: '',
    appLink:
      '',
    isTechSkills: true,
    techSkills: [
      'Nuvoton MicroControllers',
      'ST MicroControllers',
    ],
    isOtherSkills: false,
    otherSkills: [],
    isAgile: false,
    isCICD: false,
    isExperienceLetter: true,
    experienceLetterName: 'RKE Experience Letter',
    isProjects: true,
    projectName: 'Micro-Controllers Development',
    projectDescription:
      '• Provided technical consultation & circuit design optimization, reducing system failure rates by 20%.\n\n• Developed customized hardware solutions, improving efficiency and cutting costs by 15%.\n',
    isProjectDurationEnd: true,
    projectDurationStart: 'Nov 2019',
    projectDurationEnd: 'Nov 2020',
    iTSectorBased: 'Service',
    isContractor: false,
    contactorCompanyName: '',
    contactorCompanyUrl: '',
    isProductionSupport: false,
    prodSupportTools: [],
    isAwardsGiven: false,
    awards: [],
  },
  {
    id: 5,
    profileName: 'R & D Engineer',
    companyName: 'Tiyatech Solutions Pvt Ltd.',
    companyUrl: '',
    isCompanyPresentEmployee: false,
    companyDurationStart: 'Sept 2017',
    companyDurationEnd: 'Oct 2019',
    companyDescription:
      'Stabilizer Development Company',
    isAppLink: false,
    appName: '',
    appLink:
      '',
    isTechSkills: true,
    techSkills: [
      'Atmel MicroControllers',
    ],
    isOtherSkills: false,
    otherSkills: [],
    isAgile: false,
    isCICD: false,
    isExperienceLetter: true,
    experienceLetterName: 'Tiyatech Experience Letter',
    isProjects: true,
    projectName: 'Servo Voltage Stabilizer',
    projectDescription:
      '• Engineered IoT-driven automation solutions, enhancing operational efficiency.\n\n• Developed Servo Voltage Stabilizers using Atmega 16 & 32 microcontrollers, ensuring power stability.\n',
    isProjectDurationEnd: true,
    projectDurationStart: 'Sept 2017',
    projectDurationEnd: 'Oct 2019',
    iTSectorBased: 'Service',
    isContractor: false,
    contactorCompanyName: '',
    contactorCompanyUrl: '',
    isProductionSupport: false,
    prodSupportTools: [],
    isAwardsGiven: false,
    awards: [],
  },
];
