export const WorkExperienceConst = [
  {
    id: 1,
    profileName: 'React Native Developer',
    companyName: 'Scans.AI',
    companyUrl: 'https://scans.ai',
    isCompanyPresentEmployee: true,
    companyDurationStart: 'April 2026',
    companyDurationEnd: '',
    companyDescription: 'Car Scanning and Insurance Based Company',
    isAppLink: true,
    appName: 'ScansAI',
    appLink: '',
    techSkills: [
      'React Native',
      'Typescript',
      'Redux',
      'Redux-Persistent',
      'Jest',
      'Testing Library',
    ],
    otherSkills: ['Git', 'Firebase'],
    isAgile: true,
    isCICD: true,
    isExperienceLetter: false,
    experienceLetterName: '',
    isProjects: true,
    projectName: 'Ride E-Hailing',
    projectDescription:
      '• Scanning car using mobile app.\n\n• Cached Images using react-native-fast-image.\n',
    isProjectDurationEnd: false,
    projectDurationStart: 'April 2026',
    projectDurationEnd: '',
    iTSectorBased: 'Product',
    isContractor: false,
    contactorCompanyName: '',
    contactorCompanyUrl: '',
    isProductionSupport: true,
    prodSupportTools: ['Firebase Crashlytics', 'Sentry'],
    isAwardsGiven: false,
    awards: [],
  },
  {
    id: 2,
    profileName: 'Technology Lead',
    companyName: 'Infosys',
    companyUrl: 'https://www.infosys.com',
    isCompanyPresentEmployee: false,
    companyDurationStart: 'July 2021',
    companyDurationEnd: 'Mar 2026',
    companyDescription:
      'Global leader in Next-Generation Digital services, Consulting, and AI-powered Enterprise Solutions',
    isAppLink: true,
    appName: 'TractorSupply Co.',
    appLink:
      'https://play.google.com/store/apps/details?id=com.consumerapp_v1&hl=en_IN',
    techSkills: [
      'React Native',
      'Typescript',
      'Redux',
      'Restful APIs',
      'Payment Integration',
      'Google Maps',
      'Jest',
      'Testing Library',
    ],
    otherSkills: ['Git', 'Firebase', 'React DevTools', 'FlashLight', 'AEM'],
    isAgile: true,
    isCICD: true,
    isExperienceLetter: true,
    experienceLetterName: 'Infosys Relieving Letter',
    isProjects: true,
    projectName: 'Consumer Mobile App',
    projectDescription:
      '• Led the end-to-end development of a Consumer Mobile App, optimizing memory management and refining API calls, which reduced crashes by 35% and improved load speed by 30%.\n\n• Refactored Redux-based state management, modularizing reducers and improving action efficiency, which enhanced performance and reduced redundant code by 40%.\n\n• Integrated Google Maps API & third-party SDKs, enabling real-time location tracking and interactive features, which led to a 25% increase in session duration.\n\n• Spearheaded unit & integration testing using Jest and React Native Testing Library, achieving 100% test coverage and reducing post-release defects by 50%.\n\n• Automated CI/CD pipelines (Fastlane, Bitrise, GitHub Actions), cutting deployment time by 50%.\n',
    isProjectDurationEnd: true,
    projectDurationStart: 'August 2021',
    projectDurationEnd: 'Mar 2026',
    iTSectorBased: 'Service',
    isContractor: true,
    contactorCompanyName: 'TractorSupply',
    contactorCompanyUrl: 'https://www.tractorsupply.com',
    isProductionSupport: true,
    prodSupportTools: ['Firebase Crashlytics', 'Quantum Metrics', 'Dynatrace'],
    isAwardsGiven: true,
    awards: ['3P Award - Productivity, Performance & Process Excellence'],
  },
];
