export const WorkExperienceConst = [
  {
    id: 1,
    profileName: 'React Native Developer',
    companyName: 'Scans.AI',
    companyUrl: 'https://scans.ai',
    isCompanyPresentEmployee: true,
    companyDurationStart: 'April 2026',
    companyDurationEnd: '',
    companyDescription: 'Car Scanning and Insurance Based Company',
    isAppLink: true,
    appName: 'ScansAI',
    appLink: '',
    techSkills: [
      'React Native',
      'Typescript',
      'Redux',
      'Redux-Persistent',
      'Jest',
      'Testing Library',
    ],
    otherSkills: ['Git', 'Firebase'],
    isAgile: true,
    isCICD: true,
    isExperienceLetter: false,
    experienceLetterName: '',
    isProjects: true,
    projectName: 'Ride E-Hailing',
    projectDescription:
      '• Scanning car using mobile app.\n• Cached Images using react-native-fast-image.\n',
    isProjectDurationEnd: false,
    projectDurationStart: 'April 2026',
    projectDurationEnd: '',
    iTSectorBased: 'Product',
    isContractor: false,
    contactorCompany: '',
    contactorCompanyUrl: '',
    isProductionSupport: true,
    prodSupportTools: ['Firebase Crashlytics', 'Sentry'],
    isAwardsGiven: false,
    awards: [],
  },
];
