name: React Native CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      skip_tests:
        description: "Skip Unit Tests"
        required: false
        default: "false"
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  build:
    name: Setup
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Run Tests
        if: ${{github.event.inputs.skip_tests != 'true'}}
        run: npm test
  android_build:
    name: Android Build
    runs-on: macos-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Android
        run: |
          cd android
          ./gradlew assembleDebug
          cd ..
      - name: Upload Debug Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MyPortfolioAndroid.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
  ios_build:
    name: IOS Build
    runs-on: macos-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install cocoapods
        run: sudo gem install cocoapods
      - name: Install Dependencies
        run: npm ci
      - name: Prepare React Native iOS
        run: npx react-native config
      - name: Install Pods
        run: |
          cd ios
          pod deintegrate
          pod install --repo-update
          cd ..
      - name: Bundle React Native JS
        run: |
          npx react-native bundle \
            --platform ios \
            --dev false \
            --entry-file index.js \
            --bundle-output ios/main.jsbundle \
            --assets-dest ios
      - name: Show Pods Structure
        run: ls ios/Pods/Headers/Public
      - name: Build IOS
        run: |
          cd ios
          xcodebuild \
          -workspace MyPortfolioApp.xcworkspace \
          -scheme MyPortfolioApp \
          -configuration Release \
          -sdk iphoneos \
          -archivePath build/MyPortfolioApp.xcarchive \
          CODE_SIGNING_ALLOWED=NO \
          SWIFT_SERIALIZE_DEBUGGING_OPTIONS=NO \
          OTHER_SWIFT_FLAGS="-no-verify-emitted-module-interface" \
          archive
          cd ..
      - name: Create exportOptions.plist
        run: |
          cat <<EOF > ios/exportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
          "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>signingStyle</key>
            <string>automatic</string>
          </dict>
          </plist>
          EOF
      - name: Export IPA
        run: |
          cd ios
          xcodebuild -exportArchive \
          -archivePath build/MyPortfolioApp.xcarchive \
          -exportOptionsPlist exportOptions.plist \
          -exportPath build \
          CODE_SIGNING_ALLOWED=NO
          cd ..
      - name: Upload iOS IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyPortfolioIOS.ipa
          path: ios/build/*.ipa