name: Skip UT
on:
  workflow_dispatch:
concurrency:
  group: react-native-ci
  cancel-in-progress: true
env:
  NODE_VERSION: 20
jobs:
  build:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Generate Unit Test Coverage
        run: echo "Skipping Unit Test Coverage"
  android_build:
    name: Android Build
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - name: Install Dependencies
        run: npm ci
      - name: Build Android
        run: |
          cd android
          ./gradlew assembleDebug --build-cache
          cd ..
      - name: Upload Debug Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PrasoonPortfolioAndroid.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
  ios_build:
    name: IOS Build
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Install Pods
        uses: actions/cache@v4
        with:
          path: ios/pods
          key: pods-${{ runner.os }}-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            pods-${{ runner.os }}
      - name: Install cocoapods
        run: |
          sudo gem install cocoapods
          cd ios
          pod install --repo-update
          cd ..
      - name: Build IOS
        run: |
          cd ios
          xcodebuild \
          -workspace PrasoonPortfolioApp.xcworkspace \
          -scheme PrasoonPortfolioApp \
          -configuration Release \
          -sdk iphoneos \
          -destination 'generic/platform=iOS' \
          -archivePath build/PrasoonPortfolioApp.xcarchive \
          CODE_SIGNING_ALLOWED=NO \
          SKIP_INSTALL=NO \
          archive
          cd ..
      - name: Upload iOS Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PrasoonPortfolioIOS.xcarchive
          path: ios/build/PrasoonPortfolioApp.xcarchive
