name: React Native CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      skip_tests:
        description: "Skip Unit Tests"
        required: false
        default: "false"
jobs:
  build:
    name: Setup
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Install Dependencies
        run: npm ci
      - name: Upload Dependencies
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node_modules
      - name: Run Lint
        run: npm run lint
      - name: Run Tests
        if: ${{github.event.inputs.skip_tests != 'true'}}
        run: npm test
  android_build:
    name: Android Build
    runs-on: macos-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Download Dependencies
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: .
      - name: Build Android
        run: |
          cd android
          ./gradlew assembleDebug
          cd ..
  ios_build:
    name: IOS Build
    runs-on: macos-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install cocoapods
        run: sudo gem install cocoapods
      - name: Download Dependencies
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: .
      - name: Install Pods
        run: |
          cd ios
          pod install
          cd ..
      - name: Build IOS
        run: |
          cd ios
          xcodebuild \
          -workspace MyPortfolioApp.xcworkspace \
          -scheme MyPortfolioApp \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14' \
          -configuration Debug \
          -derivedDataPath build